export const books = [
  {
    title: "The Da Vinci Code",
    author: "Dan Brown",
    year: 2003,
    genre: "Thriller",
  },
  {
    title: "Gone Girl",
    author: "Gillian Flynn",
    year: 2012,
    genre: "Thriller",
  },
  {
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    year: 2005,
    genre: "Criminal",
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    year: 1997,
    genre: "Fantasy",
  },
  {
    title: "The Fellowship of the Ring",
    author: "J.R.R. Tolkien",
    year: 1954,
    genre: "Fantasy",
  },
  {
    title: "The Shining",
    author: "Stephen King",
    year: 1977,
    genre: "Thriller",
  },
  {
    title: "American Gods",
    author: "Neil Gaiman",
    year: 2001,
    genre: "Fantasy",
  },
  {
    title: "The Silence of the Lambs",
    author: "Thomas Harris",
    year: 1988,
    genre: "Thriller",
  },
  {
    title: "The Night Circus",
    author: "Erin Morgenstern",
    year: 2011,
    genre: "Fantasy",
  },
  {
    title: "Red Dragon",
    author: "Thomas Harris",
    year: 1981,
    genre: "Criminal",
  },
  {
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    year: 2007,
    genre: "Fantasy",
  },
  {
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    year: 1996,
    genre: "Fantasy",
  },
  {
    title: "The Hunger Games",
    author: "Suzanne Collins",
    year: 2008,
    genre: "Thriller",
  },
  {
    title: "The Secret History",
    author: "Donna Tartt",
    year: 1992,
    genre: "Thriller",
  },
  {
    title: "Mistborn: The Final Empire",
    author: "Brandon Sanderson",
    year: 2006,
    genre: "Fantasy",
  },
  {
    title: "Gone Tomorrow",
    author: "Lee Child",
    year: 2009,
    genre: "Thriller",
  },
  {
    title: "The Bone Collector",
    author: "Jeffery Deaver",
    year: 1997,
    genre: "Criminal",
  },
  {
    title: "In Cold Blood",
    author: "Truman Capote",
    year: 1966,
    genre: "Criminal",
  },
  {
    title: "The Lies of Locke Lamora",
    author: "Scott Lynch",
    year: 2006,
    genre: "Fantasy",
  },
  {
    title: "The Ocean at the End of the Lane",
    author: "Neil Gaiman",
    year: 2013,
    genre: "Fantasy",
  },
  {
    title: "The Girl on the Train",
    author: "Paula Hawkins",
    year: 2015,
    genre: "Thriller",
  },
  {
    title: "Before I Go to Sleep",
    author: "S.J. Watson",
    year: 2011,
    genre: "Thriller",
  },
  {
    title: "The Lightning Thief",
    author: "Rick Riordan",
    year: 2005,
    genre: "Fantasy",
  },
  {
    title: "The Blade Itself",
    author: "Joe Abercrombie",
    year: 2006,
    genre: "Fantasy",
  },
  {
    title: "Sharp Objects",
    author: "Gillian Flynn",
    year: 2006,
    genre: "Thriller",
  },
  {
    title: "Dark Places",
    author: "Gillian Flynn",
    year: 2009,
    genre: "Thriller",
  },
  {
    title: "The Way of Kings",
    author: "Brandon Sanderson",
    year: 2010,
    genre: "Fantasy",
  },
  { title: "The Martian", author: "Andy Weir", year: 2011, genre: "Thriller" },
  {
    title: "The Cuckoo's Calling",
    author: "Robert Galbraith",
    year: 2013,
    genre: "Criminal",
  },
  { title: "11/22/63", author: "Stephen King", year: 2011, genre: "Thriller" },
];
